- name: play variables
  hosts: local
  connection: local
  vars:
    COURSE: Ansible
    DURATION: 10Hours
    TRAINER: Siva
  tasks:
  - name: Print course information
    ansible.builtin.debug:
      msg: "The course is : {{ COURSE }} Duration of the course is {{ DURATION}} and the Trainer is {{ TRAINER }}" 