- name: variables from inventory
  hosts: frontend   # targetting fromtend server
  tasks:
  - name: print course info
    ansible.builtin.debug:
      msg: "Hello I am learning {{ COURSE }}, Duration: {{ DURATION }}, Trainer is: {{ TRAINER }}"