- name: playbook control using ansible facts
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx if redhat
    ansible.builtin.dnf:
      name: nginx
      state: present
      enable: yes
    when: ansible_os_family == "RedHat" 

  - name: install nginx if debian
    ansible.builtin.apt:
      name: debian
      state: present
      enable: yes
    when: ansible_os_family == "Debian"

